//@version=5
// ********** BASE SETUP **********
strategy("Trading Levels Assistant", max_labels_count = 500, max_lines_count = 500, overlay=true, initial_capital = 50000)



// ********** STRATEGY **********
var float stopLoss = na
var float takeProfit1 = na
var float takeProfit2 = na
var float takeProfit3 = na
var float stopLossShort = na
var float takeProfit1Short = na
var float takeProfit2Short = na
var float takeProfit3Short = na
var float limitLevel = na
SL = 15
TP1 = 15
TP2 = 30
TP3 = 45
stopLoss := limitLevel - SL
takeProfit1 := limitLevel + TP1 
takeProfit2 := limitLevel + TP2
takeProfit3 := limitLevel + TP3

stopLossShort := limitLevel + SL
takeProfit1Short := limitLevel - TP1
takeProfit2Short := limitLevel - TP2
takeProfit3Short := limitLevel - TP3

if systemState != systemState[1] and systemState[1] > 0 and systemState > 0 and ((systemState < 10 and systemState[1] > 10) or (systemState > 10 and systemState[1] < 10)) and validTriggerPeriod 
    strategy.close_all()
else if systemState == 0
    strategy.cancel_all()

if (buyLong or buyCross or (buyReversal and buyReversalCount > 1 )) and validTriggerPeriod
    if strategy.position_size == 0
        strategy.order("Buy", strategy.long, qty=5, limit = limitLevel)
        strategy.exit("Exit", "Buy", limit = takeProfit1, stop = stopLoss, qty = 5)

else if (sellShort or sellCross or (sellReversal and sellReversalCount > 1 )) and validTriggerPeriod
    if strategy.position_size == 0
        strategy.order("Sell", strategy.short, qty=5, limit = limitLevel)
        strategy.exit("Exit Sell1", "Sell", limit = takeProfit1Short, stop = stopLossShort, qty = 5)

// Exit for the first 2 contracts
plot(stopLossShort, "SL", strategy.position_size < 0 ? color.red : na, style = plot.style_circles)
plot(takeProfit1Short, "TP1", strategy.position_size < 0 ? color.green : na, style = plot.style_circles)
plot(takeProfit2Short, "TP2", strategy.position_size < 0 ? color.green:na, style = plot.style_circles)
plot(takeProfit3Short, "TP3", strategy.position_size < 0 ? color.green:na, style = plot.style_circles)

plot(stopLoss, "SL", strategy.position_size > 0 ? color.red : na, style = plot.style_circles)
plot(takeProfit1, "TP1", strategy.position_size > 0 ? color.green : na, style = plot.style_circles)
plot(takeProfit2, "TP2", strategy.position_size > 0 ? color.green:na, style = plot.style_circles)
plot(takeProfit3, "TP3", strategy.position_size > 0 ? color.green:na, style = plot.style_circles)